### ISSUE TITLE
solucion al path in windows

### ISSUE THREAD

**Issue by fgp555** [jonmircha/youtube-nodejs#2]
09_express_mvc  (linea 9)
11_express_ssg (linea 11)

import { fileURLToPath } from "url";
const __dirname = fileURLToPath(new URL(".", import.meta.url));

OR

import url from "url";
const __dirname = url.fileURLToPath(new URL(".", import.meta.url));

09_express_mvc (linea 9)
https://gist.github.com/fgp555/ebdd37bd48c83f9398cccdde4bd2872a

11_express_ssg (linea 11)
https://gist.github.com/fgp555/9e45fe6a7f54b911c54de8af7d2bb748

**Comment by runtimevic** [comment]
Hola:
se puede resolver asi tambien:
```javascript
const __dirname = (process.platform === "win32")
        ? path.resolve()
        : path.dirname(new URL(import.meta.url).pathname);
//const __dirname = path.dirname(new URL(import.meta.url).pathname);
```

**Comment by fgp555** [comment]
una nueva forma:

var __dirname = process.cwd();

**Comment by jonmircha** [comment]
Gracias por su ayuda ya modifique los archivos correspondientes @fgp555  y @runtimevic
